dependencies:
  - name: mysql
    repository: https://charts.helm.sh/stable
    version: 1.6.9
    condition: mysql.enabled

  - name: postgresql
    repository: https://charts.helm.sh/stable
    version: 5.3.7
    condition: postgresql.enabled

  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.3.11
    condition: mariadb.enabled
