# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: xwiki
  pullPolicy: IfNotPresent
  wikiversion: lts
## Image Tag useful when externalDB is been used
  tag: ''
service:
  portName: node
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 3000m
    memory: 6000Mi
  requests:
    cpu: 500m
    memory: 3000Mi

##
## MySql chart configuration
##
## https://github.com/helm/charts/tree/master/stable/mysql
##
mysql:
 ## Whether to deploy a mysql server. Set false for a different database.
  enabled: false
  mysqlRootPassword: xwiki
  mysqlUser: xwiki
  mysqlPassword: xwiki
  mysqlDatabase: xwiki
  imageTag: 5.7
  configurationFiles:
    mysql.cnf: |-
      [client]
      default-character-set = utf8mb4

      [mysqld]
      character-set-server = utf8mb4
      collation-server = utf8mb4_bin
      explicit_defaults_for_timestamp = 1

      [mysql]
      default-character-set = utf8mb4

## MariaDB helm chart
## https://github.com/bitnami/charts/tree/master/bitnami/mariadb
mariadb:
 ## Whether to deploy a mariadb server
  enabled: true
  auth:
    ## echo "xwiki" | base64
    rootPassword: eHdpa2kK
    username: xwiki
    ## echo "xwiki" | base64
    password: eHdpa2kK
    database: xwiki
  persistence:
    size: 20Gi
  image:
    tag: 10.5.10
  primary:
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp = 1
      basedir=/opt/bitnami/mariadb
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server = utf8mb4
      collation-server = utf8mb4_bin

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set = utf8mb4
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

      [mysql]
      default-character-set = utf8mb4

##
## Postgres chart configuration
##
## https://github.com/helm/charts/tree/master/stable/postgresql
##
postgresql:
 ## Whether to deploy a postgresql server. Set false for a different database.
  enabled: false
  postgresqlUsername: xwiki
  postgresqlPassword: xwiki
  postgresqlDatabase: xwiki
  image:
    tag: 11.3.0-debian-9-r38
  #persistence:
  #  size: 8Gi

##
## For custom mysql and postgres database. Use externalDB. 
## Would be used only if postgres and mysql is disabled.
## Set the image tag if want to use externalDB
##
externalDB:
  password: ''
  user: ''
  database: ''
  host: ''

##
## To use external solr enable solr, provide host and port
##
solr:
  enabled: true
  host: localhost
  port: 8983
  storage: 8Gi
  storageAccessMode: "ReadWriteOnce"

# To use ingress for routing set ingress.enabled value to true and istio.enabled value to false
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hostName:
  tls:

# To use istio for routing set istio.enabled value to true and ingress.enabled value to false
istio:
  enabled: false
  host: "*"

storage: "500Mi"
storageClassName: ""
storageAccessMode: "ReadWriteOnce"
deployStrategy: "Recreate"
buildID: "123"
webXmlFile: default-web.xml
xwikiCfgFile: default-xwiki.cfg
xwikiPropertiesFile: default-xwiki.properties

## Read about PostDistribution budget at https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
## Use only on a clustered setup
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1
