apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "xwiki.fullname" . }}
  labels:
    app: {{ template "xwiki.fullAppName" . }}
    version: {{ .Values.image.wikiversion }}
    {{- include "xwiki.standard-labels-no-app" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "xwiki.fullname" . }} # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: {{ template "xwiki.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "xwiki.xwikiImageName" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: JAVA_OPTS
          value: "-Xmx2048m"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "xwiki.dbSecretRefName" .}}
              key: {{ template "xwiki.dbSecretRefKey" .}}
        {{- if .Values.solr.enabled }}
        - name: INDEX_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: INDEX_HOST
        - name: INDEX_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: INDEX_PORT
        {{- end }}
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: DB_USER
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: DB_DATABASE
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: xwiki-data
          mountPath: /usr/local/xwiki
        - name: xwiki-solr-data
          mountPath: /opt/solr/server/solr
        - name: xwiki-tomcat-conf
          mountPath: /usr/local/tomcat/conf/web.xml
          subPath: web.xml
      volumes:
      - name: xwiki-solr-data
        persistentVolumeClaim:
          claimName: xwiki-solr
      - name: xwiki-data
        persistentVolumeClaim:
          claimName: xwiki
      - name: xwiki-tomcat-conf
        configMap:
          name: xwiki-tomcat-conf
          items:
          - key: web.xml
            path: web.xml

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki
  labels:
    {{- include "xwiki.standard-labels" . | nindent 4 }}
spec:
  accessModes:
    - {{.Values.storageAccessMode}}
  resources:
    requests:
      storage: {{ .Values.storage }}
    {{- if .Values.storageClass }}
    storageClassName: {{ .Values.storageClass | quote }}
    {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki-solr
  labels:
    {{- include "xwiki.standard-labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.solr.storageAccessMode}}
  resources:
    requests:
      storage: {{ .Values.solr.storage }}
    {{- if .Values.storageClass }}
    storageClassName: {{ .Values.storageClass | quote }}
    {{- end }}
