{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "xwiki.fullname" . }}
  annotations:
  {{- if .Values.ingress.annotations }}
      {{ toYaml .Values.ingress.annotations | indent 0 }}
  {{- end }}
  labels:
    {{- include "xwiki.standard-labels" . | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "xwiki.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
    {{- if .Values.ingress.hostName }}
    host: {{ .Values.ingress.hostName | quote }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls: {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end -}}