apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xwiki.fullname" . }}
  labels:
    {{- include "xwiki.standard-labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ template "xwiki.databasePassword" . }}