apiVersion: v1
kind: Service
metadata:
  name: {{ template "xwiki.fullname" . }}
  labels:
    {{- include "xwiki.standard-labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  sessionAffinity: ClientIP
  selector:
    app: {{ template "xwiki.fullname" . }}