apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "xwiki.fullname" . }}
  labels:
    app: {{ template "xwiki.fullAppName" . }}
    version: {{ .Values.image.wikiversion }}
    {{- include "xwiki.standard-labels-no-app" . | nindent 4 }}
spec:
  serviceName: {{ template "xwiki.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "xwiki.fullname" . }} # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: {{ template "xwiki.fullname" . }}
      annotations:
        timestamp: "{{ now | date "20060102150405" }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "xwiki.xwikiImageName" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: JAVA_OPTS
          value: "-Xmx2048m"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "xwiki.dbSecretRefName" .}}
              key: {{ template "xwiki.dbSecretRefKey" .}}
        {{- if .Values.solr.enabled }}
        - name: INDEX_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: INDEX_HOST
        - name: INDEX_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: INDEX_PORT
        {{- end }}
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: DB_USER
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ template "xwiki.fullname" . }}
              key: DB_DATABASE
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: xwiki-data
          mountPath: /usr/local/xwiki
        - name: xwiki-solr-data
          mountPath: /opt/solr/server/solr
        - name: xwiki-tomcat-conf
          mountPath: /usr/local/tomcat/conf/web.xml
          subPath: web.xml
        - name: xwiki-cfg
          mountPath: /usr/local/xwiki/data/xwiki.cfg
          subPath: xwiki.cfg
        - name: xwiki-properties
          mountPath: /usr/local/xwiki/data/xwiki.properties
          subPath: xwiki.properties
      volumes:
      - name: xwiki-tomcat-conf
        configMap:
          name: xwiki-tomcat-conf
          items:
          - key: web.xml
            path: web.xml
      - name: xwiki-cfg
        configMap:
          name: xwiki-cfg
          items:
          - key: xwiki.cfg
            path: xwiki.cfg
      - name: xwiki-properties
        configMap:
          name: xwiki-properties
          items:
          - key: xwiki.properties
            path: xwiki.properties
  volumeClaimTemplates:
    - metadata:
        name: xwiki-data
      spec:
        accessModes:
          - {{.Values.storageAccessMode}}
        {{- if .Values.storageClass }}
        storageClassName: {{ .Values.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage }}
    - metadata:
        name: xwiki-solr-data
      spec:
        accessModes:
          - {{.Values.solr.storageAccessMode}}
        {{- if .Values.storageClass }}
        storageClassName: {{ .Values.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.solr.storage }}
