apiVersion: v1
kind: ConfigMap
metadata:
  name: xwiki-tomcat-conf
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  web.xml: |
{{ .Files.Get .Values.webXmlFile | indent 4}}