apiVersion: v1
kind: ConfigMap
metadata:
  name: xwiki-cfg
  labels:
    {{- include "xwiki.standard-labels" . | nindent 4 }}
  annotations:
    timestamp: "{{ now | date "20060102150405" }}"    
data:
  xwiki.cfg: |
{{ .Files.Get .Values.xwikiCfgFile | indent 4}}