apiVersion: v1
kind: ConfigMap
metadata:
  name: xwiki-properties
  labels:
    {{- include "xwiki.standard-labels" . | nindent 4 }}
  annotations:
    timestamp: "{{ now | date "20060102150405" }}"    
data:
  xwiki.properties: |
{{ .Files.Get .Values.xwikiPropertiesFile | indent 4}}